//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlannerApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.WebPageStatistics = new HashSet<WebPageStatistics>();
        }
    
        public int AdminID { get; set; }
        [Required(ErrorMessage = "Field Required!")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Field Required!")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string LoginErrorMassage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebPageStatistics> WebPageStatistics { get; set; }
    }
}
