//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlannerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPageStatistics
    {
        public int WebPageStatisticsID { get; set; }
        public Nullable<int> NumberOfSoldTickets { get; set; }
        public Nullable<int> NumberOfGoingUsersToAllEvents { get; set; }
        public Nullable<int> NumberOfInterestedUsersToAllEvents { get; set; }
        public Nullable<int> NumberOfEventsMade { get; set; }
        public Nullable<int> NumberOfRegisteredUsers { get; set; }
        public Nullable<int> NumberOfRegisteredEventHosts { get; set; }
        public Nullable<decimal> TotalBalanceFromSoldTickets { get; set; }
        public Nullable<double> AvgTicketsSoldByDay { get; set; }
        public Nullable<double> AvgTicketsSoldByWeek { get; set; }
        public Nullable<double> AvgTicketsSoldByMonth { get; set; }
        public Nullable<int> IDAdmin { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
