//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventPlannerApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Going
    {
        public int GoingID { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> IDEvent { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
